const $=id=>document.getElementById(id);
const S={
en:{navCalculator:"Calculator",navStudio:"About",studioEyebrow:"ABOUT CARCOST",studioHero:"Focused digital tools. <em>Clear outcomes.</em>",studioIntro:"CarCost was built around a simple principle: useful digital tools should be clear, reliable and easy to use.",value1Title:"Purpose before complexity",value1Text:"We begin with the core user problem and avoid features that do not improve the outcome.",value2Title:"Clarity by design",value2Text:"Interfaces should make the result easy to understand without adding unnecessary cognitive load.",value3Title:"Trust through transparency",value3Text:"We communicate clearly about limitations, data handling and what the product can realistically deliver.",privacyEyebrow:"PRIVACY",privacyTitle:"Privacy by design.",privacyText:"CarCost does not require an account, password, payment card or banking information. Calculator inputs are processed in your browser and are not stored in a CarCost database.",methodologyEyebrow:"METHODOLOGY",methodologyTitle:"Transparent methodology.",methodologyText:"CarCost uses the information you provide to estimate financing, operating costs and resale value. Actual ownership costs vary by vehicle, driver, market and location.",faq1q:"Is CarCost financial advice?",faq1a:"No. It is a planning calculator designed to make costs easier to understand.",faq2q:"Do you store calculator data?",faq2a:"No CarCost database stores the values entered into the calculator.",faq3q:"Are the estimates guaranteed?",faq3a:"No. Results are planning estimates and actual ownership costs can differ.",backCalculator:"Back to calculator"},
el:{navCalculator:"Υπολογιστής",navStudio:"Σχετικά",studioEyebrow:"ΣΧΕΤΙΚΑ ΜΕ ΤΟ CARCOST",studioHero:"Στοχευμένα ψηφιακά εργαλεία. <em>Καθαρά αποτελέσματα.</em>",studioIntro:"Το CarCost βασίστηκε σε μια απλή αρχή: τα χρήσιμα ψηφιακά εργαλεία πρέπει να είναι καθαρά, αξιόπιστα και εύχρηστα.",value1Title:"Σκοπός πριν από την πολυπλοκότητα",value1Text:"Ξεκινάμε από το βασικό πρόβλημα του χρήστη και αποφεύγουμε λειτουργίες που δεν βελτιώνουν ουσιαστικά το αποτέλεσμα.",value2Title:"Καθαρότητα στον σχεδιασμό",value2Text:"Η διεπαφή πρέπει να κάνει το αποτέλεσμα εύκολο στην κατανόηση χωρίς περιττή πληροφορία.",value3Title:"Εμπιστοσύνη μέσω διαφάνειας",value3Text:"Εξηγούμε καθαρά τους περιορισμούς, τον τρόπο διαχείρισης δεδομένων και τι μπορεί ρεαλιστικά να προσφέρει το προϊόν.",privacyEyebrow:"ΑΠΟΡΡΗΤΟ",privacyTitle:"Απόρρητο από τον σχεδιασμό.",privacyText:"Το CarCost δεν απαιτεί λογαριασμό, κωδικό, κάρτα ή τραπεζικά στοιχεία. Τα στοιχεία του υπολογιστή επεξεργάζονται στον browser και δεν αποθηκεύονται σε βάση δεδομένων του CarCost.",methodologyEyebrow:"ΜΕΘΟΔΟΛΟΓΙΑ",methodologyTitle:"Διαφανής μεθοδολογία.",methodologyText:"Το CarCost χρησιμοποιεί τα στοιχεία που εισάγεις για να εκτιμήσει χρηματοδότηση, λειτουργικά έξοδα και αξία μεταπώλησης. Το πραγματικό κόστος ιδιοκτησίας διαφέρει ανά όχημα, οδηγό, αγορά και περιοχή.",faq1q:"Είναι το CarCost οικονομική συμβουλή;",faq1a:"Όχι. Είναι εργαλείο προγραμματισμού που κάνει τα κόστη πιο εύκολα στην κατανόηση.",faq2q:"Αποθηκεύετε τα δεδομένα του υπολογιστή;",faq2a:"Καμία βάση δεδομένων του CarCost δεν αποθηκεύει τις τιμές που βάζεις στον υπολογιστή.",faq3q:"Οι εκτιμήσεις είναι εγγυημένες;",faq3a:"Όχι. Τα αποτελέσματα είναι εκτιμήσεις προγραμματισμού και το πραγματικό κόστος μπορεί να διαφέρει.",backCalculator:"Πίσω στον υπολογιστή"},
"zh-CN":{navCalculator:"计算器",navStudio:"关于",studioEyebrow:"关于 CARCOST",studioHero:"专注的数字工具。<em>清晰的结果。</em>",studioIntro:"CarCost 基于一个简单原则：实用的数字工具应该清晰、可靠并且易于使用。",value1Title:"目标优先于复杂度",value1Text:"我们从核心用户问题出发，避免加入无法改善结果的功能。",value2Title:"以清晰为设计原则",value2Text:"界面应让结果更容易理解，而不是增加不必要的信息负担。",value3Title:"以透明建立信任",value3Text:"我们会清楚说明限制、数据处理方式以及产品能够现实实现的结果。",privacyEyebrow:"隐私",privacyTitle:"隐私优先设计。",privacyText:"CarCost 不需要账户、密码、支付卡或银行信息。计算器输入在浏览器中处理，不会存储在 CarCost 数据库中。",methodologyEyebrow:"方法",methodologyTitle:"透明的方法。",methodologyText:"CarCost 使用你提供的数据估算融资、运行成本和转售价值。实际持有成本会因车辆、驾驶者、市场和地区而不同。",faq1q:"CarCost 是财务建议吗？",faq1a:"不是。它是一个用于规划的计算工具，让成本更容易理解。",faq2q:"你们会存储计算器数据吗？",faq2a:"不会。CarCost 数据库不会存储你输入的计算器数值。",faq3q:"估算结果有保证吗？",faq3a:"没有。结果仅用于规划估算，实际持有成本可能不同。",backCalculator:"返回计算器"}};

function lang(){const q=new URLSearchParams(location.search).get("lang");return S[q]?q:(localStorage.getItem("carcost_lang")||"en")}
function applyLang(l){
 if(!S[l])l="en";
 localStorage.setItem("carcost_lang",l);
 document.documentElement.lang=l;
 $("language").value=l;
 document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(S[l][k])el.textContent=S[l][k]});
 document.querySelectorAll("[data-i18n-html]").forEach(el=>{const k=el.dataset.i18nHtml;if(S[l][k])el.innerHTML=S[l][k]});
 const u=new URL(location.href);u.searchParams.set("lang",l);history.replaceState(null,"",u);
}
$("language").addEventListener("change",e=>applyLang(e.target.value));
applyLang(lang());
